// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDydYU9aU3sGDF3lxcJyiEP8d2hEiBnJ4',
    appId: '1:1000153123087:web:58040725d90628c0c5967a',
    messagingSenderId: '1000153123087',
    projectId: 'quickpark-89ea0',
    authDomain: 'quickpark-89ea0.firebaseapp.com',
    storageBucket: 'quickpark-89ea0.firebasestorage.app',
    measurementId: 'G-V5ZE0GX3FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1RN7z7-pSv26AJU4oC-_4Cu9Hno2p7I',
    appId: '1:1000153123087:android:4586964494b08beac5967a',
    messagingSenderId: '1000153123087',
    projectId: 'quickpark-89ea0',
    storageBucket: 'quickpark-89ea0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDce0AobReNBGpYxBBHMMbB9Thqe4y_zfE',
    appId: '1:1000153123087:ios:e3b471f1a79c7eabc5967a',
    messagingSenderId: '1000153123087',
    projectId: 'quickpark-89ea0',
    storageBucket: 'quickpark-89ea0.firebasestorage.app',
    iosClientId: '1000153123087-j1kddlftqbecqs98j7hnlvr8ernset8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickpark',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDce0AobReNBGpYxBBHMMbB9Thqe4y_zfE',
    appId: '1:1000153123087:ios:e3b471f1a79c7eabc5967a',
    messagingSenderId: '1000153123087',
    projectId: 'quickpark-89ea0',
    storageBucket: 'quickpark-89ea0.firebasestorage.app',
    iosClientId: '1000153123087-j1kddlftqbecqs98j7hnlvr8ernset8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDydYU9aU3sGDF3lxcJyiEP8d2hEiBnJ4',
    appId: '1:1000153123087:web:36502bec3b39e140c5967a',
    messagingSenderId: '1000153123087',
    projectId: 'quickpark-89ea0',
    authDomain: 'quickpark-89ea0.firebaseapp.com',
    storageBucket: 'quickpark-89ea0.firebasestorage.app',
    measurementId: 'G-XWWNM30W3Z',
  );
}
